name: flutter_gen
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 0.0.19
komepage: https://github.com/wasabeef/flutter_gen
repository: https://github.com/wasabeef/flutter_gen
documentation: https://github.com/wasabeef/flutter_gen
issue_tracker: https://github.com/wasabeef/flutter_gen/issues
authors:
  - Daichi Furiya <dadadada.chop@gmail.com>
  - Mao Yufeng <lcdsmao@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  fluttergen: flutter_gen_command

dependencies:
  build: ^1.3.0
  args: ^1.6.0
  path: ^1.7.0
  yaml: ^2.2.1
  mime: ^0.9.7
  xml: ^4.2.0
  dart_style: ^1.3.6

dev_dependencies:
  test:
  pedantic:
  build_test:
