name: flutter_gen_runner

description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 2.0.1-dev.1
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues
authors:
  - Daichi Furiya <dadadada.chop@gmail.com>
  - Mao Yufeng <lcdsmao@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter_gen_core: ^2.0.1-dev.1
  build: '>=1.6.0 <2.0.0'

dev_dependencies:
  effective_dart: '>=1.3.0 <2.0.0'
  build_test: '>=1.3.0 <2.0.0'