name: flutter_gen_runner
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 5.9.0
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues

environment:
  sdk: ^3.0.0

dependencies:
  flutter_gen_core: 5.9.0
  build: ^2.0.0
  collection: ^1.17.0
  crypto: ^3.0.0
  glob: ^2.0.0
  path: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  lints: any # Ignoring the version to allow editing across SDK versions.
  build_test: ^2.0.0
