name: flutter_gen_core

description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 2.0.0
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues
authors:
  - Daichi Furiya <dadadada.chop@gmail.com>
  - Mao Yufeng <lcdsmao@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  path: ^1.7.0
  yaml: ^2.2.1
  mime: ^0.9.7
  xml: ^4.5.1
  dart_style: ^1.3.12
  dartx: ^0.5.0
  color: ^2.1.1
  merge_map: ^1.0.2
  json_annotation: ^3.1.1

dev_dependencies:
  test: ^1.15.7
  effective_dart: ^1.3.0
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
