name: flutter_gen_core

description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 2.0.0
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues
authors:
  - Daichi Furiya <dadadada.chop@gmail.com>
  - Mao Yufeng <lcdsmao@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: '>=1.7.0 <2.0.0'
  yaml: '>=2.2.0 <3.0.0'
  mime: '>=0.9.0 <1.0.0'
  xml: '>=4.5.0 <5.0.0'
  dart_style: '>=1.3.0 <1.4.0'
  dartx: '>=0.5.0 <1.0.0'
  color: '>=2.1.0 <3.0.0'
  merge_map: '>=1.0.0 <2.0.0'
  json_annotation: '>=3.1.0 <4.0.0'

dev_dependencies:
  test: '>=1.15.0 <2.0.0'
  effective_dart: '>=1.3.0 <2.0.0'
  build_runner: '>=1.11.0 <2.0.0'
  json_serializable: '>=3.5.0 <4.0.0'
