name: flutter_gen_core

description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 4.3.0
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues

environment:
  sdk: '>=2.14.0 <3.0.0'

version_gen:
  path: lib/

dependencies:
  path: '>=1.8.0 <2.0.0'
  yaml: '>=3.0.0 <4.0.0'
  mime: '>=1.0.0 <2.0.0'
  xml: '>=5.0.0 <7.0.0'
  dartx: '>=1.0.0 <2.0.0'
  color: '>=3.0.0 <4.0.0'
  collection: '>=1.15.0 <2.0.0'
  json_annotation: '>=4.4.0 <5.0.0'
  glob: '>=2.0.0 <3.0.0'

  dart_style: '>=2.0.0 <3.0.0'
  analyzer: '>=2.0.0 <5.0.0'
  args: '>=2.0.0 <3.0.0'
  pub_semver: '>=2.0.0 <3.0.0'
  source_span: '>=1.8.0 <2.0.0'

dev_dependencies:
  test: '>=1.16.0 <2.0.0'
  flutter_lints: '>=2.0.1 <3.0.0'
  build_runner: '>=2.0.0 <3.0.0'
  json_serializable: '>=6.0.0 <7.0.0'
  version_gen: '>=1.0.1 <2.0.0'
