name: flutter_gen_core

description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 3.1.1
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues
authors:
  - Daichi Furiya <dadadada.chop@gmail.com>
  - Mao Yufeng <lcdsmao@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: '>=1.7.0 <2.0.0'
  yaml: '>=3.0.0 <4.0.0'
  mime: '>=1.0.0 <2.0.0'
  xml: '>=5.0.0 <6.0.0'
  dartx: '>=0.6.0 <1.0.0'
  color: '>=3.0.0 <4.0.0'
  collection: '>=1.15.0 <2.0.0'
  json_annotation: '>=4.0.0 <5.0.0'

  # dart_style
  analyzer: '>=1.0.0 <2.0.0'
  args: '>=2.0.0 <3.0.0'
  pub_semver: '>=1.4.0 <3.0.0'
  source_span: '>=1.6.0 <2.0.0'

dev_dependencies:
  test: '>=1.16.0 <2.0.0'
  effective_dart: '>=1.3.0 <2.0.0'
  build_runner: '>=1.10.0 <2.0.0'
  json_serializable: '>=3.5.0 <5.0.0'
