name: flutter_gen

description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 4.1.6
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  fluttergen: flutter_gen_command

dependencies:
  flutter_gen_core: ^4.1.6
  args: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_lints: '>=1.0.4 <2.0.0'
