name: flutter_gen

description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 3.1.1
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues
authors:
  - Daichi Furiya <dadadada.chop@gmail.com>
  - Mao Yufeng <lcdsmao@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  fluttergen: flutter_gen_command

dependencies:
  flutter_gen_core: ^3.1.1
  args: '>=2.0.0 <3.0.0'

dev_dependencies:
  effective_dart: '>=1.3.0 <2.0.0'

dependency_overrides:
  flutter_gen_core:
    path: ../core
